### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by albertyou2** [66pig/face_recognition#1]
@66pig 
你好，当我配置识别的人超过3个的时候
会出现这个错误

Traceback (most recent call last):
  File "face.py", line 836, in <module>
    ui = MainWindow()
  File "face.py", line 77, in __init__
    self.get_userinfo_fromapifile()
  File "face.py", line 217, in get_userinfo_fromapifile
    self.person.append(face_recognition.face_encodings(face_recognition.load_image_file(user["avatar"]))[0])
IndexError: list index out of range

**Comment by 66pig** [comment]
你好，真的很抱歉，我平时没怎么看github，这会才看到您的消息，不知道你的问题解决没？如果还未解决的话，你可以加我QQ，我帮你看一下。到目前为止，软件的运行能够支持100多人，有可能是你配置哪里出了问题，也有可能是软件发送的http请求没有关闭（软件是有后台的）在打卡成功时也会出错，如果将http请求注释起来的话，可以本地运行。我QQ邮箱：jiarui.xing@foxmail.com

**Comment by 66pig** [comment]
> @66pig
> 你好，当我配置识别的人超过3个的时候
> 会出现这个错误
> 
> Traceback (most recent call last):
> File "face.py", line 836, in 
> ui = MainWindow()
> File "face.py", line 77, in **init**
> self.get_userinfo_fromapifile()
> File "face.py", line 217, in get_userinfo_fromapifile
> self.person.append(face_recognition.face_encodings(face_recognition.load_image_file(user["avatar"]))[0])
> IndexError: list index out of range

你好，真的很抱歉，我平时没怎么看github，这会才看到您的消息，不知道你的问题解决没？如果还未解决的话，你可以加我QQ，我帮你看一下。到目前为止，软件的运行能够支持100多人，有可能是你配置哪里出了问题，也有可能是软件发送的http请求没有关闭（软件是有后台的）在打卡成功时也会出错，如果将http请求注释起来的话，可以本地运行。我QQ邮箱：jiarui.xing@foxmail.com

**Comment by Asuna88** [comment]
这是因为你选择的avatar图像没有人脸（或者很难检测到），换几张简单的人脸图即可。

**Comment by TheTurtle2020** [comment]
> 这是因为你选择的avatar图像没有人脸（或者很难检测到），换几张简单的人脸图即可。

请问如何人脸录入啊也就是增加新的人脸！
